env:
  - DISPLAY=:99.0

before_install:
  - "sudo pip install -r requirements.txt"
  - "npm install -g npm && npm install"
  - "sh -e /etc/init.d/xvfb start"

script:
  - "mkdir build"
  - "node tasks/generate-requires.js test/spec/**/*.js > build/test_requires.js"
  - "node tasks/test.js"
  - "node tasks/build.js config/murmurhash.json build/murmurhash.min.js"
